version: '2'
services:
  api:
    build: .
    container_name: api
    restart: 'unless-stopped'
    env_file:
      - ./server/.env
    volumes:
      - vueapp:/app/frontend
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - vueapp:/app
    ports:
      - ${DOCKER_PORT}:80
volumes:
  vueapp: