FROM node:16-slim as builder

WORKDIR /builder

COPY ./ ./

RUN npm i

RUN npx prisma generate
RUN npm run build:frontend

FROM nginx:1.23.3-alpine-slim as target

WORKDIR /app

COPY --from=builder /builder/dist /app
COPY ./nginx.conf /etc/nginx/nginx.conf

ENV LOG_ENABLED=true
ENV LOG_LEVEL=debug
ENV LOGGER_NAME=fridgy

CMD ["nginx", "-g", "daemon off;"]
